// inertia/pages/blog/index.tsx
import { Link } from '@inertiajs/react'
import Seo from '~/components/seo'
import SiteLayout from '~/components/site_layout'
import type { BlogPostSummary } from '~/lib/types'

export default function BlogIndex({ posts }: { posts: BlogPostSummary[] }) {
  return (
    <SiteLayout>
      <Seo
        title="TextureLab Blog"
        description="Guides, announcements and articles about TextureLab"
      />

      <section className="block w-full bg-gray-900">
        <div className="container mx-auto px-4 text-center text-white">
          <div className="flex flex-col px-8 pt-8">
            <h1 className="mx-auto max-w-4xl pt-8 font-display text-4xl font-bold md:text-5xl">
              Welcome to TextureLab's Blog
            </h1>
            <p className="mx-auto mt-4 mb-12 max-w-lg text-xl text-gray-300 md:text-2xl">
              Guides, announcements and articles about TextureLab
            </p>
          </div>
        </div>
      </section>

      <section className="min-h-[70vh] w-full bg-gray-200 py-8">
        <div className="container mx-auto grid max-w-6xl gap-6 px-4 text-black md:grid-cols-2">
          {posts.length === 0 && (
            <p className="col-span-full py-12 text-center text-gray-600">
              No posts published yet — check back soon.
            </p>
          )}

          {posts.map((post) => (
            <article
              key={post.slug}
              className="overflow-hidden rounded-lg border border-gray-300 bg-gray-100 shadow-md"
            >
              <Link href={post.path}>
                {post.image && <img className="w-full" src={post.image} alt="" />}
                <div className="px-8 py-7">
                  <h2 className="text-left font-display text-3xl font-bold text-gray-700">
                    {post.title}
                  </h2>
                  <p className="pt-1 text-left text-gray-400">{post.dateLabel}</p>
                  <p className="pt-1 text-left">{post.description}</p>
                </div>
              </Link>
            </article>
          ))}
        </div>
      </section>
    </SiteLayout>
  )
}

// src/pages/Blog.vue
<template>
  <Layout>
    <div class="w-full bg-gray-900 block">
      <div class="container text-white text-center">
        <div class="flex flex-col pt-8 px-8">
          <h1 class="text-5xl pt-8 font-bold mx-auto max-w-4xl font-barlow">Welcome to TextureLab's Blog</h1>
          <h4 class="text-2xl mt-4 mb-12 text-gray-300 mx-auto max-w-lg">Guides, announcements and articles about TextureLab</h4>
        </div>
      </div>
    </div>
    <div class="w-full pt-8 pb-8 bg-gray-200 blog-list">
      <div class="container grid md:grid-cols-2 gap-6 text-white text-center text-black max-w-6xl">
        <div v-for="post in posts" :key="post.index"
        class="rounded-lg shadow-md overflow-hidden bg-gray-100 border border-gray-300">
        <g-link :to="post.path"
        >
          <g-image :src="post.image.src" />
          <div class="px-8 py-7">
            <h2 class="text-black text-gray-700 text-left text-3xl font-bold font-barlow">{{ post.title }}</h2>
            <h4 class="text-black text-gray-400 font-bolder text-left pt-1">{{ post.date }}</h4>
            <p class="text-black text-left pt-1">{{ post.description }}</p>
          </div>
        </g-link>
        </div>
      </div>
    </div>


  </Layout>
</template>

<page-query>
query Blog {
	blogs: allBlogPage(order: DESC, filter: { draft: { eq: false } }) {
		edges {
			node {
				id
        path
				title
				description
				image
				path
				category
				date (format: "MMMM DD, YYYY")
			}
		}
	}
}
</page-query>

<script>
export default {
  metaInfo: {
    title: 'Texturelab Blog'
  },
  computed:{
      // posts: function(){
      //   let posts = []
      //     for(let i=0;i<20;i++) {
      //       let post = {
      //         index:i,
      //         thumbail:"https://picsum.photos/600/300",
      //         category:"",
      //         date:"",
      //         author:"",
      //         summary:""
      //       }

      //       posts.push(post);
      //     }

      //     return posts;
      // },
    posts:function(){
      console.log(this.$page.blogs.edges)
      return this.$page.blogs.edges.map( ({ node })  => node);
    }
  }
}
</script>

<style>
.blog-list {
  min-height: 70vh;
}
</style>
