// inertia/components/on_this_page.tsx
import { useEffect, useState } from 'react'
import type { Heading } from '~/lib/types'

const INDENT: Record<number, string> = {
  2: 'pl-0',
  3: 'pl-2',
  4: 'pl-3',
  5: 'pl-4',
  6: 'pl-5',
}

/**
 * Table of contents for the current doc page. The active entry follows the
 * heading that is currently intersecting the top of the viewport.
 */
export default function OnThisPage({ headings, path }: { headings: Heading[]; path: string }) {
  const [activeAnchor, setActiveAnchor] = useState('')
  const entries = headings.filter((heading) => heading.depth > 1)

  useEffect(() => {
    if (window.location.hash) {
      setActiveAnchor(window.location.hash)
    }

    const observer = new IntersectionObserver(
      (intersections) => {
        // Guards against the active entry jumping around when several
        // headings enter the viewport at once (e.g. after an anchor click).
        if (intersections.length > 1) return

        const id = intersections[0]?.target.id
        if (!id) return

        setActiveAnchor(`#${id}`)
        history.replaceState(null, '', `#${id}`)
      },
      { rootMargin: '0px 0px 99999px', threshold: 1 }
    )

    document
      .querySelectorAll('.markdown h2, .markdown h3, .markdown h4, .markdown h5, .markdown h6')
      .forEach((element) => observer.observe(element))

    return () => observer.disconnect()
  }, [path])

  if (!entries.length) return null

  return (
    <div className="mt-8 border-ui-border sm:border-l sm:pb-16 sm:pl-4 md:mt-0 md:pt-12 md:pl-6 lg:pl-8">
      <h3 className="mt-0 pt-0 text-sm font-semibold tracking-wide uppercase">On this page</h3>
      <ul>
        {entries.map((heading, index) => {
          const active = activeAnchor === heading.anchor

          return (
            <li
              key={`${path}${heading.anchor}`}
              className={[
                index > 0 && heading.depth === 2
                  ? 'mt-2 border-t border-dashed border-ui-border pt-2'
                  : '',
                heading.depth === 2 ? 'font-semibold' : '',
              ].join(' ')}
            >
              <a
                href={`${path}${heading.anchor}`}
                className={`relative flex items-center py-1 text-sm transition hover:translate-x-1 ${
                  INDENT[heading.depth] ?? ''
                } ${active ? 'font-bold text-ui-primary' : ''}`}
              >
                <span
                  className={`absolute -ml-3 h-2 w-2 origin-center rounded-full bg-ui-primary transition ${
                    active ? 'scale-100 opacity-100' : 'scale-0 opacity-0'
                  }`}
                />
                {heading.value}
              </a>
            </li>
          )
        })}
      </ul>
    </div>
  )
}

// src/components/OnThisPage.vue
<template>
  <div class="mt-8 sm:pl-4 md:pl-6 md:pt-12 lg:pl-8 sm:pb-16 sm:border-l border-ui-border md:mt-0">
    <h3 class="pt-0 mt-0 text-sm tracking-wide uppercase border-none">On this page</h3>
    <div>
      <ul>
        <li
          v-for="(heading, index) in headings"
          :key="`${page.path}${heading.anchor}`"
          :class="{
            'border-t border-dashed border-ui-border pt-2 mt-2': index > 0 && heading.depth === 2,
            'font-semibold': heading.depth === 2,
            [`depth-${heading.depth}`]: true,
          }"
        >
          <g-link
            :to="`${page.path}${heading.anchor}`"
            class="relative flex items-center py-1 text-sm transition transform hover:translate-x-1"
            :class="{
              'pl-2': heading.depth === 3,
              'pl-3': heading.depth === 4,
              'pl-4': heading.depth === 5,
              'pl-5': heading.depth === 6,
              'font-bold text-ui-primary': activeAnchor === heading.anchor
            }"
          >
            <span
              class="absolute w-2 h-2 -ml-3 rounded-full opacity-0 bg-ui-primary transition transform scale-0 origin-center"
              :class="{
                'opacity-100 scale-100': activeAnchor === heading.anchor
              }"
            ></span>
            {{ heading.value }}
          </g-link>
        </li>
      </ul>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      activeAnchor: '',
      observer: null
    }
  },

  computed: {
    page() {
      return this.$page.docPage;
    },
    headings() {
      return this.page.headings.filter(h => h.depth > 1);
    }
  },

  watch: {
    $route: function() {
      if (process.isClient && window.location.hash) {
        this.activeAnchor = window.location.hash;
      }

      // Clear the current observer.
      this.observer.disconnect();

      // And create another one for the next page.
      this.$nextTick(this.initObserver);
    }
  },

  methods: {
    observerCallback(entries, observer) {
      // This early return fixes the jumping
      // of the bubble active state when we click on a link.
      // There should be only one intersecting element anyways.
      if (entries.length > 1) {
        return;
      }

      const id = entries[0].target.id;

      // We want to give the link of the intersecting
      // headline active and add the hash to the url.
      if (id) {
        this.activeAnchor = '#' + id;

        if (history.replaceState) {
          history.replaceState(null, null, '#' + id);
        }
      }
    },

    initObserver() {
      this.observer = new IntersectionObserver(this.observerCallback, {
        // This rootMargin should allow intersections at the top of the page.
        rootMargin: '0px 0px 99999px',
        threshold: 1
      });

      const elements = document.querySelectorAll(
        '.content h2, .content h3, .content h4, .content h5, .content h6'
      );

      for (let i = 0; i < elements.length; i++) {
        this.observer.observe(elements[i]);
      }
    },
  },

  mounted() {
    if (process.isClient) {
      if (window.location.hash) {
        this.activeAnchor = window.location.hash;
      }
      this.$nextTick(this.initObserver);
    }
  }
};
</script>
